main:
    random_seed: 'nips2019'
    saved_dir: '/home/tungi/viewport-cluster-predictor/models/fair2/train'
    # loaded_path: '/home/tungi/viewport-cluster-predictor/models/fair/train/checkpoints/model_16.pth'
dataset:
    name: 'VPClusterDataset'
    kwargs:
        data_dir: '/home/tungi/datasets/ViewportData/Out'
        train_preprocessings:
            - name: 'Normalize'
        valid_preprocessings:
            - name: 'Normalize'
        transforms:
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 32
        valid_batch_size: 32
        shuffle: true
        num_workers: 8

net:
    name: 'VPClusterNet'
    kwargs:
        in_channels: 3
        # out_channels: 12
        
losses:
    - name: 'MyMSELoss'
      weight: 1.0
    # - name: WeightedMSELoss
    #   weight: 1.0
    # - name: 'SphericalDistanceLoss'
    #   weight: 1000.
    # - name: 'ProbabilityLoss'
    #   weight: 100.

metrics:
    - name: 'SphericalDistance'
    - name: 'MeanSquareErrorProb'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 8
        gamma: 0.95


logger:
    name: 'VPClusterLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'SphericalDistance'
        saved_freq: 2
        early_stop: 0

trainer:
    name: 'VPClusterTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 32
