main:
    random_seed: 'nips2019'
    saved_dir: '/home/tungi/viewport-cluster-predictor/models/sphloss/train'

dataset:
    name: 'VPClusterDataset'
    kwargs:
        data_dir: '/home/tungi/datasets/ViewportData/Out'
        train_preprocessings:
            - name: 'Normalize'
        valid_preprocessings:
            - name: 'Normalize'
        transforms:
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 32
        valid_batch_size: 16
        shuffle: true
        num_workers: 8

net:
    name: 'VPClusterNet'
    kwargs:
        in_channels: 3
        out_channels: 12
        
losses:
    # - name: 'SphericalDistanceLoss'
    #   weight: 0.1
    - name: 'ProbabilityLoss'
      weight: 0.3
    - name: WeightedMSELoss
      weight: 0.7
    # - name: 'SphericalDistanceLoss'
    #   weight: 1000.
    # - name: 'ProbabilityLoss'
    #   weight: 100.

metrics:
    - name: 'SphericalDistance'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.01
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 1
        gamma: 0.95


logger:
    name: 'VPClusterLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 2
        early_stop: 0

trainer:
    name: 'VPClusterTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 48
