main:
    random_seed: 'nips2019'
    saved_dir: '/home/tungi/viewport-cluster-predictor/models/vpcluster/train'

dataset:
    name: 'VPClusterDataset'
    kwargs:
        data_dir: '/home/tungi/datasets/ViewportData/Out'
        train_preprocessings:
            - name: 'Normalize'
        valid_preprocessings:
            - name: 'Normalize'
        transforms:
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 8
        valid_batch_size: 4
        shuffle: true
        num_workers: 8

net:
    name: 'VPCNet'
    kwargs:
        in_channels: 3
        out_channels: 12
        
losses:
    - name: 'WeightedMSELoss'
      weight: 1.0

metrics:
    - name: 'SphericalDistance'
    - name: 'MSE'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'VPClusterLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'VPClusterTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 100
